# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

    global:
        PYTHON: "C:\\conda"
        MINICONDA_VERSION: ""
        CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
        PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                          # of 32 bit and 64 bit builds are needed, move this
                          # to the matrix section.
        CONDA_DEPENDENCIES: "scipy numpy nose h5py astropy>=3 matplotlib statsmodels"
        PIP_DEPENDENCIES: "emcee pytest-catchlog"

    matrix:
        - PYTHON_VERSION: "3.6"
          NUMPY_VERSION: "1.16"
          CONDA_PY: "36"
        - PYTHON_VERSION: "3.7"
          NUMPY_VERSION: "1.16"
          CONDA_PY: "37"

matrix:
    fast_finish: true

platform:
    -x64

install:
    - "git clone --depth 1 git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

# Not a .NET project, we build Astropy in the install step instead
build: false

test_script:
    - "%CMD_IN_ENV% python setup.py test"
